### PR TITLE
Usecases cleanup

### PR DESCRIPTION
**Pull request by lboeman**
I added some spacing around the header elements, and made it so that there is some padding around the images on large screens so they don't take up the whole page. 

I did reorganize the header values such that they flow from large to small starting with the page title. I will need to update the other page's titles to h1 as well, perhaps in another pr to the main repo?

There is a "To top" link in the lower right corner that is always present.

I pushed this to master on my repo as well so you can see it at http://lboeman.github.io

### CODE REVIEW

**Comment by wholmgren** [comment]
I like the changes a lot. Up to you on h1 updates. Does it make more sense to do it all together here?

**Comment by lboeman** [comment]
Sure, I think probably at this point it's not *really* important to try to compartmentalize those types of changes is the git history.

**Comment by wholmgren** [comment]
@lboeman ready to merge?

**Comment by lboeman** [comment]
Yep, good to go!

**Comment by wholmgren** [comment]
thanks

**Pull request merged**
